"""Register the test-only assembly when extraScriptingDefines omits it from Unity's load list.

Only audit build metadata is edited. Gameplay DLLs, assets and release outputs are untouched.
The RuntimeInitializeOnLoads entry must already have been generated by Unity.
"""
import hashlib
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
campaign = sys.argv[1] if len(sys.argv) > 1 else 'SystemFix0927'
assert campaign in ('SystemAudit0927', 'SystemFix0927')
records = []
for role, app in [('Client','UnityFpsClient'),('Server','UnityFpsDedicatedServer')]:
    data = root/'Builds'/campaign/role/(app+'_Data')
    init = json.loads((data/'RuntimeInitializeOnLoads.json').read_text())
    assert any(x['assemblyName']=='Game.RuntimeAudit' and x['methodName']=='Boot' for x in init['root'])
    path = data/'ScriptingAssemblies.json'
    original = path.read_bytes()
    config = json.loads(original)
    if 'Game.RuntimeAudit.dll' not in config['names']:
        assert len(config['names'])==len(config['types'])
        (root/'Logs'/campaign/('audit-'+role+'-ScriptingAssemblies.original.json')).write_bytes(original)
        config['names'].append('Game.RuntimeAudit.dll')
        config['types'].append(16)
        path.write_text(json.dumps(config,separators=(',',':')),encoding='utf-8')
    records.append(dict(role=role,loadListSha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                        driverSha256=hashlib.sha256((data/'Managed/Game.RuntimeAudit.dll').read_bytes()).hexdigest(),
                        operation='explicit test assembly registration', gameplayModified=False))
(root/'Logs'/campaign/'audit-package-registration.json').write_text(json.dumps(records,indent=2),encoding='utf-8')
print(json.dumps(records))
