// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnityFps.Api.Data;

#nullable disable

namespace UnityFps.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829141120_AddWeaponCommerce")]
    partial class AddWeaponCommerce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UnityFps.Api.Data.CatalogItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CalibrationKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsImplemented")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<long>("PriceCoins")
                        .HasColumnType("bigint");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("CatalogItem", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.MatchRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("XpEarned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PlayedAtUtc");

                    b.ToTable("MatchRecord", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerInventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerInventoryItem", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PrimaryWeaponId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SecondaryWeaponId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ThrowableId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerLoadout", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadoutAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AttachmentSlot")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<long>("LoadoutId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeaponSlot")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("LoadoutId", "WeaponSlot", "AttachmentSlot")
                        .IsUnique();

                    b.ToTable("PlayerLoadoutAttachment", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SkillPoints")
                        .HasColumnType("int");

                    b.Property<int>("UpAmmoCap")
                        .HasColumnType("int");

                    b.Property<int>("UpDamage")
                        .HasColumnType("int");

                    b.Property<int>("UpMaxHealth")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("PlayerProfile", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerWallet", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("PlayerWallet", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.ShopPurchase", b =>
                {
                    b.Property<string>("PurchaseId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("TotalPriceCoins")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitPriceCoins")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ShopPurchase", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.WalletLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DeltaCoins")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("WalletLedgerEntry", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.MatchRecord", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany("Matches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerInventoryItem", b =>
                {
                    b.HasOne("UnityFps.Api.Data.CatalogItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadout", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithOne("Loadout")
                        .HasForeignKey("UnityFps.Api.Data.PlayerLoadout", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadoutAttachment", b =>
                {
                    b.HasOne("UnityFps.Api.Data.PlayerLoadout", "Loadout")
                        .WithMany("Attachments")
                        .HasForeignKey("LoadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerProfile", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithOne("Profile")
                        .HasForeignKey("UnityFps.Api.Data.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerWallet", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("UnityFps.Api.Data.PlayerWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.ShopPurchase", b =>
                {
                    b.HasOne("UnityFps.Api.Data.CatalogItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadout", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("UnityFps.Api.Data.UserAccount", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("Loadout");

                    b.Navigation("Matches");

                    b.Navigation("Profile");

                    b.Navigation("Purchases");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
