// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnityFps.Api.Data;

#nullable disable

namespace UnityFps.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908153904_CFWaitingRoomLifecycle")]
    partial class CFWaitingRoomLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UnityFps.Api.Data.AchievementDefinition", b =>
                {
                    b.Property<string>("AchievementId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("PassXpReward")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TargetMetric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.HasKey("AchievementId");

                    b.ToTable("AchievementDefinition", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.AttachmentCompat", b =>
                {
                    b.Property<string>("WeaponItemId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AttachmentItemId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CalibrationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsImplemented")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("WeaponItemId", "AttachmentItemId");

                    b.HasIndex("AttachmentItemId");

                    b.ToTable("AttachmentCompat", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.CatalogItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AcquisitionSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CalibrationKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsImplemented")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<long>("PriceCoins")
                        .HasColumnType("bigint");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("CatalogItem", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.GameRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentMatchId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("HostAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("HostPort")
                        .HasColumnType("int");

                    b.Property<long>("HostUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("HostUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JoinedPlayers")
                        .HasColumnType("int");

                    b.Property<int>("KillTarget")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastMatchId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("MatchGeneration")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<long>("RoomVersion")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServerInstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StateChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.HasIndex("ServerInstanceId");

                    b.HasIndex("Status", "StateChangedAtUtc");

                    b.ToTable("GameRoom", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.GameRoomMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<ulong>("ChatJoinSeq")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsReady")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GameRoomMember", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.MatchRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientMatchId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<bool>("IsWin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("PassXpEarned")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("XpEarned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId", "ClientMatchId")
                        .IsUnique();

                    b.HasIndex("UserId", "PlayedAtUtc");

                    b.ToTable("MatchRecord", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PassReward", b =>
                {
                    b.Property<string>("SeasonId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("PassLevel")
                        .HasColumnType("int");

                    b.Property<int>("CoinsAmount")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("SeasonId", "PassLevel");

                    b.ToTable("PassReward", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerAchievement", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AchievementId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("GrantedPassXp")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnlockedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "AchievementId");

                    b.ToTable("PlayerAchievement", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerInventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerInventoryItem", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PrimaryWeaponId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SecondaryWeaponId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ThrowableId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerLoadout", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadoutAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AttachmentSlot")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<long>("LoadoutId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeaponSlot")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("LoadoutId", "WeaponSlot", "AttachmentSlot")
                        .IsUnique();

                    b.ToTable("PlayerLoadoutAttachment", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerPass", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeasonId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("PassLevel")
                        .HasColumnType("int");

                    b.Property<int>("PassXp")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "SeasonId");

                    b.ToTable("PlayerPass", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerPassRewardGrant", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeasonId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("PassLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "SeasonId", "PassLevel");

                    b.ToTable("PlayerPassRewardGrant", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SkillPoints")
                        .HasColumnType("int");

                    b.Property<int>("UpAmmoCap")
                        .HasColumnType("int");

                    b.Property<int>("UpDamage")
                        .HasColumnType("int");

                    b.Property<int>("UpMaxHealth")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("PlayerProfile", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerWallet", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("PlayerWallet", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.RoomMatchResult", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlayersJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<DateTime?>("RewardsAppliedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("WinnerTeam")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("MatchId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomMatchResult", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.RoomMatchRoster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeftAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("MatchId", "UserId")
                        .IsUnique();

                    b.ToTable("RoomMatchRoster", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.ServerInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BuildVersion")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPlayers")
                        .HasColumnType("int");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId")
                        .IsUnique();

                    b.HasIndex("RoomCode");

                    b.HasIndex("State", "LastHeartbeatUtc");

                    b.ToTable("ServerInstance", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.ServerJoinTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<long>("ServerInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("TicketHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("RoomCode");

                    b.HasIndex("ServerInstanceId");

                    b.HasIndex("TicketHash")
                        .IsUnique();

                    b.ToTable("ServerJoinTicket", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.ShopPurchase", b =>
                {
                    b.Property<string>("PurchaseId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("TotalPriceCoins")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitPriceCoins")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ShopPurchase", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.UserSetting", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("SettingKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "SettingKey");

                    b.ToTable("UserSetting", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.WalletLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DeltaCoins")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("WalletLedgerEntry", (string)null);
                });

            modelBuilder.Entity("UnityFps.Api.Data.AttachmentCompat", b =>
                {
                    b.HasOne("UnityFps.Api.Data.CatalogItem", "AttachmentItem")
                        .WithMany()
                        .HasForeignKey("AttachmentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnityFps.Api.Data.CatalogItem", "WeaponItem")
                        .WithMany()
                        .HasForeignKey("WeaponItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttachmentItem");

                    b.Navigation("WeaponItem");
                });

            modelBuilder.Entity("UnityFps.Api.Data.GameRoom", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "Host")
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnityFps.Api.Data.ServerInstance", "ServerInstance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Host");

                    b.Navigation("ServerInstance");
                });

            modelBuilder.Entity("UnityFps.Api.Data.GameRoomMember", b =>
                {
                    b.HasOne("UnityFps.Api.Data.GameRoom", "Room")
                        .WithMany("Members")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.MatchRecord", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany("Matches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerInventoryItem", b =>
                {
                    b.HasOne("UnityFps.Api.Data.CatalogItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadout", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithOne("Loadout")
                        .HasForeignKey("UnityFps.Api.Data.PlayerLoadout", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadoutAttachment", b =>
                {
                    b.HasOne("UnityFps.Api.Data.PlayerLoadout", "Loadout")
                        .WithMany("Attachments")
                        .HasForeignKey("LoadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loadout");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerPass", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany("Passes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerProfile", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithOne("Profile")
                        .HasForeignKey("UnityFps.Api.Data.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerWallet", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("UnityFps.Api.Data.PlayerWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.RoomMatchRoster", b =>
                {
                    b.HasOne("UnityFps.Api.Data.GameRoom", "Room")
                        .WithMany("Rosters")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("UnityFps.Api.Data.ServerJoinTicket", b =>
                {
                    b.HasOne("UnityFps.Api.Data.ServerInstance", "Instance")
                        .WithMany()
                        .HasForeignKey("ServerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("UnityFps.Api.Data.ShopPurchase", b =>
                {
                    b.HasOne("UnityFps.Api.Data.CatalogItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.UserSetting", b =>
                {
                    b.HasOne("UnityFps.Api.Data.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UnityFps.Api.Data.GameRoom", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Rosters");
                });

            modelBuilder.Entity("UnityFps.Api.Data.PlayerLoadout", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("UnityFps.Api.Data.UserAccount", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("Loadout");

                    b.Navigation("Matches");

                    b.Navigation("Passes");

                    b.Navigation("Profile");

                    b.Navigation("Purchases");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
